### ISSUE TITLE
ChargeException The Card Holder was not authorised, this is used in 3-D authorization

### ISSUE THREAD

**Issue by lazicah** [PaystackHQ/paystack-android#77]
# Problem/Motivation
Having Difficulty in completing payments using the Paystack Sdk

## Actual Results:
The Card Holder was not authorised, this is used in 3-D authorization

**Comment by steveamaza** [comment]
This isn't an SDK issue but a transaction failure because the customer's card hasn't been activated for [3D Secure ](https://paystack.helpscoutdocs.com/article/128-what-is-3-domain-secure-3ds). You can find the transaction on your Dashboard at https://dashboard.paystack.com/#/transactions?page=1. Advise the customer to contact their bank
