### ISSUE TITLE
Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by chuksdsilent** [PaystackHQ/paystack-android#97]
I am developing and android application and I integrated paystack on the platform but it is showing this error. I don't know what could be the cause

**Comment by michael-paystack** [comment]
Hello,
From the title, I assume you're trying to get the length of text from an uninitialized string variable.
Without some more context, I can't provide any more insights.

I'm closing this issue because it's been dormant for a while.
Please open a new issue if this still needs to be addressed.
Thanks
